### PR TITLE
Feature/jetut 120 rename faces pages

### PR DESCRIPTION
**Pull request by jhammen**

### CODE REVIEW

**Comment by kito99** [comment]
@jhammen  Ok, now I remember where I was with this.  These changes look fine, but take a look at the versions of these files in the `main` branch. Note that the JSF ones have been renamed and updated, but there is no history because the rename wasn't done with `git`. I wanted to rename the files so that when we merge with `main` we can preserve the history. That's what `renamer.sh` is for, although I mistyped the description (just updated it). That script doesn't change the directory names, though, which it should (or those can be changed manually).

That being said, for the merge to the main branch, it's worth pointing out that some other content (like the Faces) content has been updated in that branch since `release/9.1.`. I'm not sure if they best way to handle this is to just rerun all the scripts on the `main` branch or to actually merge in the changes from the `asciidoc` folder. I suspect the former is better, and then just comparing the two.

**Comment by jhammen** [comment]
So if I get it: the files in main were renamed jsf -> faces outside of git, and then content modified.. Now you want to do that same rename, using git this time, in this branch, before merging to 9.1? If so is there a reason why we can't go ahead and do that?

**Comment by kito99** [comment]
@jhammen nah, I think going ahead and renaming them using the script is good. I think that was my plan.

**Comment by jhammen** [comment]
Files/folders renamed and links updated, this is now ready to merge

**Review by kito99 — APPROVED** [review]

**Pull request merged**
