### PR TITLE
Feature/jetut 138 migrate enterprise beans

### PR DESCRIPTION
**Pull request by jhammen**

### CODE REVIEW

**Comment by kito99** [comment]
@jhammen no need to create a PR if you're just merging into your feature branch

**Review by kito99 — APPROVED** [review]
Looks good, but in general please to a git `mv` rather than a normal mv so the history of files is preserved (I'm talking about src/main/asciidoc/ejb-gettingstarted/ejb-gettingstarted001.adoc).

**Comment by jhammen** [comment]
> Looks good, but in general please to a git `mv` rather than a normal mv so the history of files is preserved (I'm talking about src/main/asciidoc/ejb-gettingstarted/ejb-gettingstarted001.adoc).

it was moved via git mv along with all the others:

https://github.com/virtua-tech/jakartaee-tutorial/pull/40/commits/874ecd8554e96d6015816deb1e083ebf7b5db3a8

I don't know why the github diff tool misrepresents this fact..

**Comment by kito99** [comment]
Ah ok

**Pull request merged**
