### PR TITLE
JETUT-53: Specify diagram font and colors

### PR DESCRIPTION
**Pull request by BalusC**
https://virtua.atlassian.net/browse/JETUT-53

### CODE REVIEW

**Comment by kito99** [comment]
So in practice how would this work? They draw the entire diagram and then select all and change the styles? Or they change the style for one element and then select “Set style as default” (not sure if that is the exact name of the option)? 

What I like about specifying the style from the Styles tab is that it gets applied to everything automatically.

**Comment by kito99** [comment]
So in practice how would this work? They draw the entire diagram and then select all and change the styles? Or they change the style for one element and then select “Set style as default” (not sure if that is the exact name of the option)? 

What I like about specifying the style from the Styles tab is that it gets applied to everything automatically.

**Comment by kito99** [comment]
Yeah, I saw that, but I think it's only for the commercial version for Atlassian Cloud. I ran across this: https://github.com/jgraph/drawio/issues/3255. Not promising...

**Review by kito99 — CHANGES_REQUESTED** [review]
Can you leave out the build artifacts?

**Review by kito99 — APPROVED** [review]

**Comment by BalusC** [comment]
> Can you leave out the build artifacts?

Not understanding this. These are part of release/10 branch which this PR was supposed to be merged into ...

**Comment by kito99** [comment]
@BalusC I mentioned this elsewhere (ticket or PR; I can't remember), but the Antora folks recommend using the main branch for the current release, so when I was setting up the Antora build, I took the build artifacts from the `release/10` branch and made some changes. So there are newer versions already in `main`.

**Pull request closed without merging**
